"use strict";

export const countriesOfUE = {
  Alemania: "Germany",
  Austria: "Austria",
  Bélgica: "Belgium",
  Bulgaria: "Bulgaria",
  Chipre: "Cyprus",
  Croacia: "Croatia",
  Dinamarca: "Denmark",
  Eslovaquia: "Slovakia",
  Eslovenia: "Slovenia",
  España: "Spain",
  Estonia: "Estonia",
  Finlandia: "Finland",
  Francia: "France",
  Grecia: "Greece",
  Hungría: "Hungary",
  Irlanda: "Ireland",
  Italia: "Italy",
  Letonia: "Latvia",
  Lituania: "Lithuania",
  Luxemburgo: "Luxembourg",
  Malta: "Malta",
  "Países Bajos": "Netherlands",
  Polonia: "Poland",
  Portugal: "Portugal",
  "República Checa": "Czechia",
  Rumanía: "Romania",
  Suecia: "Sweden",
};
